export enum AIJobStatus {
  QUEUED = "QUEUED",

  PREPROCESSING = "PREPROCESSING",

  DETECTING_POSE = "DETECTING_POSE",

  SEGMENTING = "SEGMENTING",

  TRYON = "TRYON",

  FINISHED = "FINISHED",

  FAILED = "FAILED",
}